### ISSUE TITLE
incorporating feedback from coverage

### ISSUE THREAD

**Issue by regehr** [regehr/uniform-tree-sampling#5]
so it should be pretty straightforward for us to guide a generator using coverage, we simply need some outside mechanism to label test cases that we've already generated as being worthy of further mutation (since they drive the SUT to its coverage frontier or whatever) or unworthy (since they don't do interesting stuff). basically we just pick a random point in the decision tree of a good test case and proceed randomly from there. the issue is that once we diverge from the existing path, the entire rest of the generation is likely to be totally different. this is in contrast to what we really want which is a smallish change to the test case.

to say the same thing another way, let's say this sequence of choices led to a test case that we'd like to mutate further:
```
34 2 6 2 3 6  6 2 3 56 1 1 0
```
we'll randomly decide that the second 6 should become a 10, and at that point we're in terra incognita for the rest of this test case:
```
34 2 6 2 3 10 ??????????????
```
there's nothing wrong with this, it might work sometimes, but I suspect we can do better. alas, I think we'll need help from the generator.

so what if we got the generator to let us know about "scopes" in the decision tree, denoted like so:
```
34 2 ( 6 2 3 6 ) ( 6 ( 17 3 ) ) 56 1 1 0
```
what this means is that (17 3) is a scope where if we change the 17 to something else, the 3 might go away, it might become a binary coin flip, it might turn into a string of 12 decisions, but after whatever happens is done. we'll go back to the 56 and then the rest of the test case. in other words, this mutation will effect some sort of localized change to the test case instead of just wildly going down a different branch of the decision tree.

this is all not hard to support on our side, but it could be arbitrarily painful on the generator side. we'll just have to see if our clients can provide this kind of scoping feature.

**Comment by alcides** [comment]
(I'm probably not supposed to chime in, but since I work on similar problems... Let me know if I'm out of place here and you'd rather work on this without external noise, please).

Representing test-cases as a sequence of numbers is popular in GP as [Grammatical Evolution](https://en.wikipedia.org/wiki/Grammatical_evolution). The representation can be limited to X integers, and you go around if you need more.

A variation of this approach is [Dynamic Structured Grammatical Evolution](https://www.researchgate.net/publication/332549077_Structured_grammatical_evolution_A_dynamic_approach) that splits the list in sub-lists, one for each grammar production (or generator, in your case).  This keeps the reproducibility of reconstructing the same individual, and keeps information about what changes are relevant for each generator, even if it changes for others.

If each generator has an internal ID, this should be quite straightforward to implement. Changing the 17 in your example would not throw away the rest of the lists, as they might be useful for repeating the same decisions, but maybe a bit further down the tree.

**Comment by DRMacIver** [comment]
Tracking nested scoping is also a thing in Hypothesis, although we mostly only use it for test-case reduction (and increasingly not for that). Agreed that it's a good thing to support if we want to do some more complicated manipulation of the generator. When we did the Csmith integration we introduced a `HYPOTHESIS_DRAW` macro which you can see e.g. in https://github.com/HypothesisWorks/csmith/blob/master/src/Statement.cpp#L274 which calls `TargetClass::draw` with the remaining arguments, bracketed with the relevant start and stop function calls.

I suspect however we might be surprised at how good a more simple coverage guided testing is without these. Hypothesis supports using standard unstructured fuzzers like AFL using this interface, and it's generally pretty good https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/core.py#L932 - you get to systematically explore enough points of divergence that generally you'll luck into something that works.

@Zac-HD would know more about this - I've not been paying all that much attention to fuzzing in Hypothesis, but my impression was that it worked pretty well even with AFL. I don't know what https://hypofuzz.com/ is doing (his latest efforts)

**Comment by Zac-HD** [comment]
I started looking into this, but never got to the point that it was lower-hanging fruit than using a better generic fuzzing algorithm.  E.g. "randomly regenerate a single span" seems neat, but taking a prefix, suffix, and random infix without worrying about whether it matched up seems to work pretty well too 😅

The indispensable thing is to support custom coverage, in my case via `hypothesis.target()` and `hypothesis.event()` - that allows you to run the IJON algorithms, and incidentally emulate coverage-guided fuzzing of literally anything else that your fuzz harness can measure (e.g. grammar coverage of the generator, state-space-coverage of a formal model you're checking traces against, etc.).

But personally I'd just start by hooking up `libAFL` as the backend - you'll want to evaluate against it anyway, and it'll be plenty powerful enough to let you focus on other problems for a while.

**Comment by regehr** [comment]
thanks for the feedback, everyone!

there's a working custom mutator for afl++ now, and also some support for scoping, but not quite as much as I'd like, but I'm going to close this
